site_name: Perdoo
site_url: https://perdoo.readthedocs.io/en/latest/
site_description: A Python application to help sort and organize your comic collection.
site_author: Jonah Jackson

copyright: GPL-3.0

repo_url: https://github.com/Buried-In-Code/Perdoo
repo_name: Buried-In-Code/Perdoo

theme:
  name: material
  favicon: img/favicon.ico
  features:
    - content.code.copy
    - navigation.expand
    - navigation.top
  icon:
    repo: material/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: material/github
      link: https://github.com/Buried-In-Code
    - icon: material/mastodon
      link: https://fosstodon.org/@BuriedInCode
    - icon: simple/matrix
      link: https://matrix.to/#/#The-Dev-Environment:matrix.org

markdown_extensions:
  - pymdownx.highlight:
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.superfences


nav:
  - Home: index.md
  - perdoo:
      - Package: perdoo/__init__.md
      - exceptions: perdoo/exceptions.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: True
            show_root_full_path: False
            show_category_heading: True
            # Docstrings
            docstring_style: google
            docstring_section_style: spacy
            line_length: 100
            merge_init_into_class: True
            show_signature_annotations: True
            # Additional
            show_source: False
  - include-markdown
